
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';

export const DATABASE_CONNECTION = 'DATABASE_CONNECTION'
export const USER_REPOSITORY = 'USER_REPOSITORY';

export const TESTING_REPOSITORY='TESTING_REPOSITORY'

export const APPLICATION_USER_MENU_REPOSITORY = 'APPLICATION_USER_MENU_REPOSITORY'
export const APPLICATION_USER_SUBMENU_REPOSITORY = 'APPLICATION_USER_SUBMENU_REPOSITORY'
export const APPLICATION_USER_MENU_MAP_REPOSITORY = 'APPLICATION_USER_MENU_MAP_REPOSITORY'
export const APPLICATION_USER_MENU_MAP_TEMP_REPOSITORY = 'APPLICATION_USER_MENU_MAP_TEMP_REPOSITORY'

export const APPLICATION_USER_REPOSITORY = 'APPLICATION_USER_REPOSITORY'
export const APPLICATION_USER_TEMP_REPOSITORY = 'APPLICATION_USER_TEMP_REPOSITORY'
export const APPLICATION_USER_HISTORY_REPOSITORY = 'APPLICATION_USER_HISTORY_REPOSITORY'


export const BDDIVISION_REPO = 'BDDIVISION_REPO'
export const BDDISTRICT_REPO = 'BDDISTRICT_REPO'
export const BDTHANA_REPO = 'BDTHANA_REPO'

export const ADMIN_USER_ROLE = 'ADMIN_USER_ROLE'
export const ADMIN_USER_ROLE_TEMP='ADMIN_USER_ROLE_TEMP'
export const ADMIN_USER_ROLE_HISTORY='ADMIN_USER_ROLE_HISTORY'

export const RILAC_MODULE_REPO = 'RILAC_MODULE_REPO'
export const MODULE_APPROVAL_ROLE_MAP_REPO = 'MODULE_APPROVAL_ROLE_MAP_REPO'
export const MODULE_APPROVAL_ROLE_MAP_TEMP_REPO = 'MODULE_APPROVAL_ROLE_MAP_TEMP_REPO'
export const MODULE_APPROVAL_ROLE_MAP_HISTORY_REPO = 'MODULE_APPROVAL_ROLE_MAP_HISTORY_REPO'


export const ADMINUSER_PASSWORDHISTORY_REPO = 'ADMINUSER_PASSWORDHISTORY_REPO'